# Generated by Django 4.1.5 on 2023-01-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40)),
                ('imgfile', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField()),
            ],
        ),
    ]
